### ISSUE TITLE
Suggestion: Add a new global env variable to yaml config in appveyor

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/Suite#139]
https://ci.appveyor.com/account/open-systems-pharmacology-ci/tools/global-yaml

now
```
environment:
  ospsuite_version: '12.0'
  APPVEYOR_BLOCK_DOTNETCORE_TESTS_AUTORUN: true
```

update to

```
environment:
  ospsuite_version: '12.0'
  ospsuite_nightly_version: '12.0'
  APPVEYOR_BLOCK_DOTNETCORE_TESTS_AUTORUN: true
```

where ospsuite_nightly_version will only be used in `appveyor_nightly.yml` files
